Repository automl/amltk, pull requests merged in 2023-12, with the labels that each got.

#179 doc: update CONTRIBUTING.md with installation instructions for Windows.
  .pre-commit-config.yaml
  CONTRIBUTING.md
Labels: documentation

#193 fix(rich): Move import into scoped block
  src/amltk/pipeline/node.py
Labels: bug

#194 doc: Fixup indentation preventing view
  src/amltk/pipeline/builders/sklearn.py
Labels: documentation

#195 fix(pipeline): configure only operates on chosen choice
  src/amltk/pipeline/components.py
  tests/pipeline/test_configuring.py
Labels: bug

#200 fix(data): `reduce_int_span` with nullable dtypes
  src/amltk/data/dtype_reduction.py
  tests/data/test_dtype_reduction.py
Labels: bug

#201 refactor(Scheduling): `limit` -> `max_calls`
  docs/guides/scheduling.md
  src/amltk/scheduling/events.py
  src/amltk/scheduling/task.py
Labels: ux
