Repository automl/amltk, pull requests merged in 2024-04, with the labels that each got.

#276 Add functionality to construct a PyTorch Model from a pipeline
  pyproject.toml
  src/amltk/exceptions.py
  src/amltk/pipeline/node.py
  src/amltk/pytorch/__init__.py
  src/amltk/pytorch/builders.py
  src/amltk/pytorch/pytorch_example.py
  tests/pytorch/__init__.py
  tests/pytorch/common.py
  tests/pytorch/test_build_model_from_pipeline.py
  tests/pytorch/test_match_chosen_dimensions.py
  tests/pytorch/test_match_dimensions.py
Labels: feature

#278 doc: Fix bad tooltip numbering
  examples/hpo_with_ensembling.py
Labels: documentation

#282 fix: Pass in sampler to `create_study`
  src/amltk/optimization/optimizers/optuna.py
Labels: bug

#283 doc(CVEvaluator): Example of `CVEvalautor` with `RandomSearch`
  examples/sklearn-hpo-cv.py
  src/amltk/optimization/optimizers/random_search.py
  src/amltk/scheduling/task.py
  src/amltk/sklearn/evaluation.py
  src/amltk/store/stored.py
Labels: documentation
